### ISSUE TITLE
Questions about retrieval stage

### ISSUE THREAD

**Issue by RUiN-jiarun** [v-pnk/cadloc#1]
Thanks for sharing the benchmark!  
I've got a question on your MeshLoc visual localization process. In the paper you've mentioned that if we only have a 3D model of the scene and no database images, we use the rendered images as the database images. So the image retrieval stage used the **rendered images** rather than **real images**?
I wonder how this method performances since low textured CAD model may lead to bad retrieval results.

**Comment by v-pnk** [comment]
Thank you for your interest in our work!
The results presented in the paper use synthetically generated database camera poses ([Fig. 5a](https://arxiv.org/pdf/2304.05947.pdf#figure.caption.7)) for which we don't have real images, just the renderings. Therefore the retrieval stage for each real query image searches for the most similar rendered database image. Low fidelity models influence both the retrieval and matching stage, but estimating which model is more suitable for a deep-learning global descriptor ([AP-GeM](https://github.com/naver/deep-image-retrieval) in our case) based on how the model looks is not that straightforward.

When taking the pose of the single best retrieved database image:
![notre_dame_ap-gem_best_of_1](https://github.com/v-pnk/cadloc/assets/44996094/c9058f6e-a2cf-47aa-a6b9-8cb5b45f26e6)

When taking the best database pose out of 20 retrieved (using oracle):
![notre_dame_ap-gem_best_of_20](https://github.com/v-pnk/cadloc/assets/44996094/11c82e30-9c3d-421a-8289-8c291d9a2ed9)

The CAD models for reference:
![image](https://github.com/v-pnk/cadloc/assets/44996094/f13a3722-9923-40cc-9e23-dc37f2f632d6)

Used AP-GeM checkpoint: Resnet101-AP-GeM-LM18

**Comment by RUiN-jiarun** [comment]
Thanks for your reply! However the result in paper (Fig. 4(a))
![image](https://github.com/v-pnk/cadloc/assets/64483405/0189f533-7538-4088-94d1-81d3014c8d0b)
 shows a better performance than that in top-20 retrieved best pose
![image](https://github.com/v-pnk/cadloc/assets/64483405/0e233e43-3349-4b28-b84b-ecba741d020e)  
So what is the configuration of MeshLoc to represent the results in paper? For example get a 99% success rate on achieving less than 10% DCRE error as you've presented in the paper

**Comment by v-pnk** [comment]
The plots in my previous comment use poses of the retrieved database images without the subsequent P3P pose estimation.

The plots from the  paper use the retrieval only to get shortlist of database images, which are then used for local feature matching and P3P pose estimation.

**Comment by RUiN-jiarun** [comment]
Oh I got it. Thanks a lot!
